matrix1 <- matrix(c(3,9,-1,4,2,6), nrow = 2)
print(matrix1)
matrix2 <- matrix(c(5,2,0,9,4,3), nrow = 2)
print(matrix2)
results <- (matrix1 * matrix2)
cat("result of multiplication","\n")
print(results)
results <-(matrix1 / matrix2)
cat("result of devision","\n")
print(results)